"""Adiciona chave Pix, status e timestamp

Revision ID: 680b3fd90160
Revises: 1dc3e75ecd4c
Create Date: 2025-02-12 13:31:27.342168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680b3fd90160'
down_revision = '1dc3e75ecd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_key', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('status')
        batch_op.drop_column('recipient_key')

    # ### end Alembic commands ###
